services:
  dashboard:
    # http://192.168.1.58:42069/
    build: .
    container_name: hydra-dashboard
    ports:
      - '42069:42069'
    volumes:
      - ./variables.json:/app/variables.json:ro
      - ./src:/app/src:ro
    env_file:
      - .env
    depends_on:
      - glances
    restart: unless-stopped

  glances:
    # http://192.168.1.58:61208/
    image: nicolargo/glances:latest-full
    container_name: hydra-glances
    pid: host
    privileged: true
    ports:
      - '61208:61208'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    environment:
      - GLANCES_OPT=-w --bind 0.0.0.0 --disable-webui --quiet
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"
    restart: unless-stopped

  bentopdf:
    # http://192.168.1.58:42070/
    image: ghcr.io/alam00000/bentopdf:latest
    ports:
      - '42070:42070'
    restart: unless-stopped
